apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "file-manager-server.fullname" . }}
  labels:
    {{- include "file-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    workerServiceGrpcPort: {{ .Values.workerServiceGrpcPort }}
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    enableFileUpload: {{ .Values.enableFileUpload }}
    {{- if .Values.global.objectStore.s3.bucket }}
    objectStore:
      s3:
        endpointUrl: {{ .Values.global.objectStore.s3.endpointUrl }}
        region: {{ .Values.global.objectStore.s3.region }}
        insecureSkipVerify: {{ .Values.global.objectStore.s3.insecureSkipVerify }}
        bucket: {{ .Values.global.objectStore.s3.bucket }}
        pathPrefix: {{ .Values.objectStore.s3.pathPrefix }}
        {{- with .Values.global.objectStore.s3.assumeRole }}
        {{- if .roleArn }}
        assumeRole:
          roleArn: {{ .roleArn }}
          externalId: {{ .externalId }}
        {{- end }}
        {{- end }}
    {{- end }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
      ssl:
        mode: {{ .Values.global.database.ssl.mode }}
        rootCert: {{ .Values.global.database.ssl.rootCert }}
      createDatabase: {{ .Values.global.database.createDatabase }}
      originalDatabase: {{ .Values.global.database.originalDatabase }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
    usageSender:
      {{- toYaml .Values.global.usageSender | nindent 6 }}
