// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FilesServiceClient is the client API for FilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesServiceClient interface {
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*File, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
}

type filesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesServiceClient(cc grpc.ClientConnInterface) FilesServiceClient {
	return &filesServiceClient{cc}
}

func (c *filesServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, "/llmariner.files.server.v1.FilesService/ListFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/llmariner.files.server.v1.FilesService/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/llmariner.files.server.v1.FilesService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesServiceServer is the server API for FilesService service.
// All implementations must embed UnimplementedFilesServiceServer
// for forward compatibility
type FilesServiceServer interface {
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	GetFile(context.Context, *GetFileRequest) (*File, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	mustEmbedUnimplementedFilesServiceServer()
}

// UnimplementedFilesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilesServiceServer struct {
}

func (UnimplementedFilesServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFilesServiceServer) GetFile(context.Context, *GetFileRequest) (*File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFilesServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFilesServiceServer) mustEmbedUnimplementedFilesServiceServer() {}

// UnsafeFilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesServiceServer will
// result in compilation errors.
type UnsafeFilesServiceServer interface {
	mustEmbedUnimplementedFilesServiceServer()
}

func RegisterFilesServiceServer(s grpc.ServiceRegistrar, srv FilesServiceServer) {
	s.RegisterService(&FilesService_ServiceDesc, srv)
}

func _FilesService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.files.server.v1.FilesService/ListFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.files.server.v1.FilesService/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilesService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.files.server.v1.FilesService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesService_ServiceDesc is the grpc.ServiceDesc for FilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.files.server.v1.FilesService",
	HandlerType: (*FilesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFiles",
			Handler:    _FilesService_ListFiles_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _FilesService_GetFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FilesService_DeleteFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/file_manager_service.proto",
}

// FilesWorkerServiceClient is the client API for FilesWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesWorkerServiceClient interface {
	GetFilePath(ctx context.Context, in *GetFilePathRequest, opts ...grpc.CallOption) (*GetFilePathResponse, error)
}

type filesWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesWorkerServiceClient(cc grpc.ClientConnInterface) FilesWorkerServiceClient {
	return &filesWorkerServiceClient{cc}
}

func (c *filesWorkerServiceClient) GetFilePath(ctx context.Context, in *GetFilePathRequest, opts ...grpc.CallOption) (*GetFilePathResponse, error) {
	out := new(GetFilePathResponse)
	err := c.cc.Invoke(ctx, "/llmariner.files.server.v1.FilesWorkerService/GetFilePath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesWorkerServiceServer is the server API for FilesWorkerService service.
// All implementations must embed UnimplementedFilesWorkerServiceServer
// for forward compatibility
type FilesWorkerServiceServer interface {
	GetFilePath(context.Context, *GetFilePathRequest) (*GetFilePathResponse, error)
	mustEmbedUnimplementedFilesWorkerServiceServer()
}

// UnimplementedFilesWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilesWorkerServiceServer struct {
}

func (UnimplementedFilesWorkerServiceServer) GetFilePath(context.Context, *GetFilePathRequest) (*GetFilePathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilePath not implemented")
}
func (UnimplementedFilesWorkerServiceServer) mustEmbedUnimplementedFilesWorkerServiceServer() {}

// UnsafeFilesWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesWorkerServiceServer will
// result in compilation errors.
type UnsafeFilesWorkerServiceServer interface {
	mustEmbedUnimplementedFilesWorkerServiceServer()
}

func RegisterFilesWorkerServiceServer(s grpc.ServiceRegistrar, srv FilesWorkerServiceServer) {
	s.RegisterService(&FilesWorkerService_ServiceDesc, srv)
}

func _FilesWorkerService_GetFilePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesWorkerServiceServer).GetFilePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.files.server.v1.FilesWorkerService/GetFilePath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesWorkerServiceServer).GetFilePath(ctx, req.(*GetFilePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesWorkerService_ServiceDesc is the grpc.ServiceDesc for FilesWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.files.server.v1.FilesWorkerService",
	HandlerType: (*FilesWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilePath",
			Handler:    _FilesWorkerService_GetFilePath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/file_manager_service.proto",
}

// FilesInternalServiceClient is the client API for FilesInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesInternalServiceClient interface {
	GetFilePath(ctx context.Context, in *GetFilePathRequest, opts ...grpc.CallOption) (*GetFilePathResponse, error)
}

type filesInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesInternalServiceClient(cc grpc.ClientConnInterface) FilesInternalServiceClient {
	return &filesInternalServiceClient{cc}
}

func (c *filesInternalServiceClient) GetFilePath(ctx context.Context, in *GetFilePathRequest, opts ...grpc.CallOption) (*GetFilePathResponse, error) {
	out := new(GetFilePathResponse)
	err := c.cc.Invoke(ctx, "/llmariner.files.server.v1.FilesInternalService/GetFilePath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesInternalServiceServer is the server API for FilesInternalService service.
// All implementations must embed UnimplementedFilesInternalServiceServer
// for forward compatibility
type FilesInternalServiceServer interface {
	GetFilePath(context.Context, *GetFilePathRequest) (*GetFilePathResponse, error)
	mustEmbedUnimplementedFilesInternalServiceServer()
}

// UnimplementedFilesInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFilesInternalServiceServer struct {
}

func (UnimplementedFilesInternalServiceServer) GetFilePath(context.Context, *GetFilePathRequest) (*GetFilePathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilePath not implemented")
}
func (UnimplementedFilesInternalServiceServer) mustEmbedUnimplementedFilesInternalServiceServer() {}

// UnsafeFilesInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesInternalServiceServer will
// result in compilation errors.
type UnsafeFilesInternalServiceServer interface {
	mustEmbedUnimplementedFilesInternalServiceServer()
}

func RegisterFilesInternalServiceServer(s grpc.ServiceRegistrar, srv FilesInternalServiceServer) {
	s.RegisterService(&FilesInternalService_ServiceDesc, srv)
}

func _FilesInternalService_GetFilePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesInternalServiceServer).GetFilePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmariner.files.server.v1.FilesInternalService/GetFilePath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesInternalServiceServer).GetFilePath(ctx, req.(*GetFilePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesInternalService_ServiceDesc is the grpc.ServiceDesc for FilesInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmariner.files.server.v1.FilesInternalService",
	HandlerType: (*FilesInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilePath",
			Handler:    _FilesInternalService_GetFilePath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/file_manager_service.proto",
}
